#!/usr/bin/python3
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright 2026 Jiamu Sun <barroit@linux.com>
#

import sys

def print_no_lf(*args):
	print(*args, end = '')

print(f'/* generated by {sys.argv[0]} */')
print(f'const {sys.argv[1]} = [')

prev_year = 3939
first_year = 1
next = 0

for line in sys.stdin:
	if not line:
		break

	line = line.rstrip('\n')
	var, val = line.split(':\t', 1)

	year_col = var.split('_', 2)
	year = f'20{year_col[1][1:]}'

	if prev_year != year:
		if not first_year:
			print(' ],')

		print_no_lf(f'\t[ {year}, ')
		first_year = 0
		prev_year = year
		first_val = 1

	if next == 0:
		if not first_val:
			print_no_lf(', ')
		print_no_lf(f"[ '{val}', ")
	else:
		print_no_lf(f"'{val}' ]")

	next ^= 1
	first_val = 0

print(' ],')
print(']')
