#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

printf '/* generated by %s */\n' $0
printf 'const notice_map = [\n'

while read file; do
	printf "\t[ '%s', " $file | sed 's/README\.txt/*/'
	printf "'%s' ],\n" $file | tr [:lower:]/. [:upper:]__
done

printf ']\n'
