#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

printf '/* generated by %s */\n' $0
printf 'const license_map = [\n'

while read file; do
	printf "\t[ '%s', " $(basename $file)
	printf "'%s' ],\n" $file
done

printf ']\n'
