#!/usr/bin/python3
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright 2026 Jiamu Sun <barroit@linux.com>
#

import re
import sys

def print_no_lf(*args):
	print(*args, end = '')

print(f'/* Generated by {sys.argv[0]} */')
print('const history = [')

first_year = 1
next_work = 1

for line in sys.stdin:
	if not line:
		break
	elif line == '\n':
		continue

	line = line.rstrip('\n')
	year_match = re.search(r'\[\[(\d{4})\]\]', line)

	if year_match:
		year = year_match.group(1)

		if not first_year:
			print('] ],')
			print_no_lf(f'\t[ {year}, ')
		else:
			print_no_lf(f'\t[ {year}, ')

		first_year = 0
		first_work = 1
		continue

	if next_work:
		if not first_work:
			print_no_lf(f"], [ '{line}', ")
		else:
			print_no_lf(f"[ '{line}', ")
	else:
		print_no_lf(f"'{line}' ")

	next_work ^= 1
	first_work = 0

print('] ],')
print(']')
